Models/ErrorViewModel.cs
namespace OrderApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Filter.cs
namespace OrderApp.Models
{
    public class Filter
    {
        public DateTime? FromDate { get; set; } = DateTime.Now.AddMonths(-1);

        public DateTime? ToDate { get; set; } = DateTime.Now;
        
        public int? ProviderId { get; set; }
        
        public string? Number { get; set; }
        
        public string? Name { get; set; }
        
        public decimal? Quantity { get; set; }
        
        public string? Unit { get; set; }

        public IQueryable<Order> Apply(IQueryable<Order> orders, IQueryable<OrderItem> items)
            => from order in orders
               where
               // Date filter
               (!this.FromDate.HasValue || order.Date > this.FromDate.Value) &&
               (!this.ToDate.HasValue || order.Date < this.ToDate.Value) &&

               // Provider filter
               (!this.ProviderId.HasValue || order.ProviderId == this.ProviderId.Value) &&

               // Number filter
               (string.IsNullOrEmpty(this.Number) || order.Number == this.Number) &&

               // Contains item filter
               (string.IsNullOrEmpty(this.Name) && !this.Quantity.HasValue && string.IsNullOrEmpty(this.Unit) ||
               items.Any(item =>
               item.OrderId == order.Id &&
               (string.IsNullOrEmpty(this.Name) || item.Name == this.Name) &&
               (!this.Quantity.HasValue || item.Quantity == this.Quantity) &&
               (string.IsNullOrEmpty(this.Unit) || item.Unit == this.Unit)))

               select order;
    }
}

Models/Order.cs
using System.ComponentModel.DataAnnotations;

namespace OrderApp.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        public string Number { get; set; }

        public DateTime Date { get; set; }

        public int ProviderId { get; set; }
    }
}

Models/OrderItem.cs
using System.ComponentModel.DataAnnotations;

namespace OrderApp.Models
{
    public class OrderItem
    {
        [Key]
        public int Id { get; set; }

        public int OrderId { get; set; }

        public string Name { get; set; }

        public decimal Quantity { get; set; }

        public string Unit { get; set; }
    }
}

Models/Provider.cs
using System.ComponentModel.DataAnnotations;

namespace OrderApp.Models
{
    public class Provider
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OrderApp.Context;
using OrderApp.Models;
using System.Diagnostics;

namespace OrderApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationContext _db;

        public HomeController(ApplicationContext _db)
        {
            this._db = _db;
        }

        public IActionResult Index(Filter filter)
        {
            ViewBag.Orders = filter.Apply(this._db.Orders.AsQueryable(), this._db.OrderItems.AsQueryable()).ToArray();
            ViewBag.Providers = this._db.Providers.ToArray();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using OrderApp.Context;
using OrderApp.Models;

namespace OrderApp.Controllers
{
    public class OrderController : Controller
    {
        private ApplicationContext _db;

        public OrderController(ApplicationContext db)
        {
            this._db = db;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int id)
        {
            var order = await this._db.Orders.FindAsync(id);
            if (order is null)
            {
                return BadRequest();
            }

            ViewBag.Order = order;
            ViewBag.OrderItems = this._db.OrderItems.Where(item => item.OrderId == order.Id);
            ViewBag.Providers = this._db.Providers.ToArray();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Order model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            await this._db.Orders.AddAsync(model);
            await this._db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var order = await this._db.Orders.FindAsync(id);
            if (order is null)
            {
                return BadRequest();
            }

            // Delete order items
            foreach (var item in this._db.OrderItems.Where(item => item.OrderId == order.Id))
            {
                this._db.OrderItems.Remove(item);
            }

            // Delete order
            this._db.Orders.Remove(order);

            await this._db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Order model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            this._db.Orders.Update(model);
            await this._db.SaveChangesAsync();
            return RedirectToAction("Index", "Order", new { id = model.Id });
        }
    }
}

Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Mvc;
using OrderApp.Context;
using OrderApp.Models;

namespace OrderApp.Controllers
{
    public class OrderItemController : Controller
    {
        private ApplicationContext _db;

        public OrderItemController(ApplicationContext db)
        {
            this._db = db;
        }

        public async Task<IActionResult> Delete(int id)
        {
            var item = await this._db.OrderItems.FindAsync(id);
            if (item is null)
            {
                return BadRequest();
            }

            var orderId = item.OrderId;
            this._db.OrderItems.Remove(item);
            await this._db.SaveChangesAsync();
            return RedirectToAction("Index", "Order", new { id = orderId });
        }

        [HttpPost]
        public async Task<IActionResult> Create(int orderId, OrderItem model)
        {
            model.OrderId = orderId;

            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            await this._db.OrderItems.AddAsync(model);
            await this._db.SaveChangesAsync();
            return RedirectToAction("Index", "Order", new { id = orderId });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

<!-- Table -->
<table class="table mb-5">
    <thead>
        <tr>
            <th scope="col">Number</th>
            <th scope="col">Date</th>
            <th scope="col">Provider</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in ViewBag.Orders)
        {
            <tr onclick="location.href='@(Url.Action("Index", "Order", new { id = order.Id }))'">
                <td>@order.Number</td>
                <td>@order.Date</td>
                <td>@(((Provider[])ViewBag.Providers).First(p => p.Id == order.ProviderId).Name)</td>
            </tr>
        }
    </tbody>
</table>

<div class="text-center">
    <partial name="_PartialFiltration"/>
    
    <button type="button" class="btn btn-primary mt-5" data-bs-toggle="modal" data-bs-target="#createOrder">
        Create new order
    </button>
</div>


<partial name="_PartialAddOrder"/>
@section Scripts{
@{
    <partial name="_ValidationScriptsPartial"/>
}
}

Views/Order/Index.cshtml
@{
    ViewData["Title"] = "Order";
    var order = (Order)ViewBag.Order;
}

<div class="card text-center m-2">
    <div class="card-header">@(((Provider[])ViewBag.Providers).First(p => p.Id == order.ProviderId).Name)</div>

    <div class="card-body">
        <h5 class="card-title">@order.Number</h5>

        <ul class="list-group list-group-flush">
            <!-- Item list -->
            @foreach (var item in ViewBag.OrderItems)
            {
                <li class="list-group-item">
                    <div class="input-group">
                        <input class="form-control" value="@item.Name" disabled readonly/>
                        <input class="form-control" value="@item.Quantity" disabled readonly>
                        <input class="input-group-text" value="@item.Unit" disabled readonly/>
                        <a 
                            class="btn btn-primary input-group-text"
                            href="@Url.Action("Delete", "OrderItem", new { id = item.Id })"
                        >
                            <i class="bi bi-cart-dash" style="font-size: 1.5rem;"></i>
                        </a>
                    </div>
                </li>
            }

            <!-- Create item -->
            <li class="list-group-item">
                <partial name="_PartialAddOrderItem"/>
            </li>


        </ul>
    </div>

    <div class="card-footer text-muted">@order.Date</div>
</div>

<div class="text-end">
    <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editOrder">Edit</a>
    <a href="@Url.Action("Delete", "Order", new { id = @order.Id })" class="btn btn-danger">Delete</a>
</div>


<partial name="_PartialEditOrder" model="@order"/>

@section Scripts{
@{
    <partial name="_ValidationScriptsPartial"/>
}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrderApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/OrderApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OrderApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OrderApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_PartialAddOrder.cshtml
@model Order

<div class="modal fade" id="createOrder" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" asp-action="Create" asp-controller="Order">
                <div class="modal-header">
                    <h5 class="modal-title">Create new order</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
            
                <div class="modal-body">

                    <div class="input-group mb-3">
                        <input asp-for="Number" class="form-control" placeholder="Number" required/>
                    </div>

                    <div class="input-group mb-3">
                        <input asp-for="Date" class="form-control" pplaceholder="Date" required/>
                    </div>

                    <div class="input-group mb-3">
                        <select asp-for="ProviderId" class="form-select" asp-items="@(new SelectList(ViewBag.Providers, "Id", "Name"))"></select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Shared/_PartialAddOrderItem.cshtml
@model OrderItem
@{
    var order = (Order)ViewBag.Order;
}

<form method="post" asp-action="Create" asp-controller="OrderItem" asp-route-orderId="@order.Id">    
    <div class="input-group">
        <input asp-for="Name" class="form-control" placeholder="Name" required/>
        <input asp-for="Quantity" class="form-control" placeholder="Quantity" type="number" required>
        <input asp-for="Unit" class="input-group-text" placeholder="Unit" required/>
        <button class="btn btn-primary input-group-text" type="submit">
            <i class="bi bi-cart-plus" style="font-size: 1.5rem;"></i>
        </button>
    </div>
</form>

Views/Shared/_PartialEditOrder.cshtml
@model Order

<div class="modal fade" id="editOrder" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" asp-action="Edit" asp-controller="Order">
                <div class="modal-header">
                    <h5 class="modal-title">Edit order</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <div class="input-group mb-3">
                        <input asp-for="Number" class="form-control" placeholder="Number" required/>
                    </div>

                    <div class="input-group mb-3">
                        <input asp-for="Date" class="form-control" pplaceholder="Date" required/>
                    </div>

                    <div class="input-group mb-3">
                        <select asp-for="ProviderId" class="form-select" asp-items="@(new SelectList(ViewBag.Providers, "Id", "Name"))"></select>
                    </div>

                    <input asp-for="Id" required hidden/>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Shared/_PartialFiltration.cshtml
@model Filter

<form method="get" asp-action="Index" asp-controller="Home">
    <!-- Date filter -->
    <div class="input-group p-1">
        <span class="input-group-text" name="from">From</span>
        <input asp-for="FromDate" class="form-control">
        <input asp-for="ToDate" class="form-control">
        <span class="input-group-text">To</span>
    </div>

    <div class="input-group p-1">
        <!-- Provider filter -->
        <select asp-for="ProviderId" asp-items="@(new SelectList(ViewBag.Providers, "Id", "Name"))" class="form-select">
            <option selected>-- Provider --</option>
        </select>
        
        <!-- Number filter -->
        <input asp-for="Number" class="form-control" placeholder="Number"/>
    </div>

    <!-- Contains item filter -->
    <div class="input-group p-1">
        <input asp-for="Name" class="form-control" placeholder="Name"/>
        <input asp-for="Quantity" class="form-control" placeholder="Quantity" type="number"/>
        <input asp-for="Unit" class="form-control" placeholder="Unit"/>
    </div>

    <button class="btn btn-outline-primary" type="submit">Filter</button>
</form>